services:
  client:
    container_name: ${T_BENCH_TASK_DOCKER_CLIENT_CONTAINER_NAME}
    image: ${T_BENCH_TASK_DOCKER_CLIENT_IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TEST_DIR=${T_BENCH_TEST_DIR:-/tests}
    stdin_open: true
    tty: true
